---
# Purpose
# The task file dynamically creates the variables used in the hadoop configuration template files.
# 
# Important Notes:
# The calling playbook will use an include statement to include this file, but the use of include
# will be removed in Ansible 2.8:  http://docs.ansible.com/ansible/latest/include_module.html
# 
# It is recommended that the use of include be replaced by import* and include*, such as
# include_tasks, import_playbook, import_tasks.  Unfortunately, such items are not available
# until version 2.4, and version 2.0 is what is currently included in the Ubuntu repo.


# dynamic variables to provide the template files with proper data directory structures
# now, using debug and with_sequence create a sequence variable that will store the
# result of each debug statement for each iteration of with_sequence.
#
# these sequence variables are then processed into lists (below) and assigned to a variable 
# that can be referenced in the jinja temlate file to create configuration files 
# hdfs-site.xml and mapred-site.xml

  - name: create sequence variable dfs_namenode_name_dir_seq
    debug: msg={{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/{{ hadoop_dfs_namenode_name_dir }}
    with_sequence: start=1 end={{ hadoop_num_drives_per_node }}
    register: dfs_namenode_name_dir_seq

  - name: create sequence variable dfs_namenode_data_dir_seq
    debug: msg={{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/{{ hadoop_dfs_datanode_data_dir }}
    with_sequence: start=1 end={{ hadoop_num_drives_per_node }}
    register: dfs_datanode_data_dir_seq

  - name: create sequence variable dfs_namenode_checkpoint_dir_seq
    debug: msg={{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/{{ hadoop_dfs_namenode_checkpoint_dir }}
    with_sequence: start=1 end={{ hadoop_num_drives_per_node }}
    register: dfs_namenode_checkpoint_dir_seq

  - name: create sequence variable yarn_nodemanager_local_dirs_seq
    debug: msg={{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/{{ yarn_nodemanager_local_dirs }}
    with_sequence: start=1 end={{ hadoop_num_drives_per_node }}
    register: yarn_nodemanager_local_dirs_seq

  - name: create sequence variable mapred_cluster_local_dir_seq
    debug: msg={{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/{{ mapreduce_cluster_local_dir }}
    with_sequence: start=1 end={{ hadoop_num_drives_per_node }}
    register: mapreduce_cluster_local_dir_seq


# since, mapred/system is a single directory, its path has been created as a variable in the
# set_fact: section below.

# create lists of strings that will be assigned to variables that will be used in the
# xml configuration files
  - set_fact:
      dfs_namenode_name_dir_list: "{{ dfs_namenode_name_dir_seq.results | map(attribute='msg') | join(',') }}"
      dfs_datanode_data_dir_list: "{{ dfs_datanode_data_dir_seq.results | map(attribute='msg') | join(',') }}"
      dfs_namenode_checkpoint_dir_list: "{{ dfs_namenode_checkpoint_dir_seq.results | map(attribute='msg') | join(',') }}"
      yarn_nodemanager_local_dirs_list: "{{ yarn_nodemanager_local_dirs_seq.results | map(attribute='msg') | join(',') }}"
      mapreduce_cluster_local_dir_list: "{{ mapreduce_cluster_local_dir_seq.results | map(attribute='msg') | join(',') }}"


