---
# Set this to 'true' and specify a Git repository if you want to deploy Drupal
# to your server from an existing repository.
#drupal_deploy: false
drupal_deploy: true
#drupal_deploy_repo: ""
drupal_deploy_repo: "https://github.com/drupal/drupal.git"
#drupal_deploy_repo: "git@github.com:drupal/drupal.git"
#drupal_deploy_version: master
# try this with "7.x" too
drupal_deploy_version: "7.57"
drupal_deploy_update: true

#drupal_deploy_dir: "/var/www/drupal"
# drupal_deploy_dir: "/var/www/vhosts/localhost/drupal"
# keep in sync with geerlingguy.apache/vars/main.yml, geerlingguy.drupal/vars/main.yml
drupal_deploy_dir: "/var/www/vhosts/localhost/boa"

#drupal_deploy_accept_hostkey: no
drupal_deploy_accept_hostkey: yes
drupal_deploy_composer_install: yes

# Set this to 'true' and 'drupal_build_composer*' to 'false' if you would like
# to build a Drupal make file with Drush.
drupal_build_makefile: false
drush_makefile_path: "/path/to/drupal.make.yml"
drush_make_options: "--no-gitinfofile"

# Set 'drupal_build_makefile' to 'false' and this to 'true' if you are using a
# Composer-based site deployment strategy.
drupal_build_composer: false
drupal_composer_path: "/path/to/drupal.composer.json"
drupal_composer_install_dir: "{{ drupal_deploy_dir }}"
drupal_composer_dependencies:
  - "drupal/devel:1.x-dev"

# *******************************
# tasks/build-composer-project.ym. 
# - name: Generate Drupal project with composer package in /tmp/composer-project (this may take a while).
#  command: >
#    {{ composer_path }} create-project
#
# was complaining that -> fatal: [drupal-master2]: FAILED! => {"failed": true, "msg": "ERROR! 'composer_path' is undefined"}
# I thought that perhaps it was a typo and sb named drupal_composer_path, as no composer_path is defined in all of the drupal files
# ,but drupal_composer_path is defined and using it led to other errors.
#
# I'm starting with the default values for all variables, except for ones such as drupal_deploy_version: 7.x, etc...
#
# Searching with +geerlingguy.drupal +composer_path +undefined I found several references to composer_path: /usr/bin/composer
# in several geerlingguy.drupal-vm issue reports.  eg.  https://github.com/geerlingguy/drupal-vm/issues/1039
# I think geerlingguy.drupal-vm is related to his work with vagrant.
#
# So, I'm going to try using composer_path: /usr/local/bin/composer, which is where composer was installed on my test machine.
composer_path: /usr/local/bin/composer
# *******************************


# Set this to 'true' and 'drupal_build_makefile', 'drupal_build_composer' to
# 'false' if you are using Composer's create-project as a site deployment
# strategy.
drupal_build_composer_project: true
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
#drupal_composer_project_package: "drupal-composer/drupal-project:7.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

# Required Drupal settings.
drupal_core_path: "{{ drupal_deploy_dir }}/web"
drupal_core_owner: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
drupal_db_user: drupal
drupal_db_password: drupal

# ****
drupal_db_name: drupal
# try using example_db for the moment, bc that was the default value for the database name when running the geerlingguy.mysql role
# drupal_db_name: example_db
# ****

drupal_db_backend: mysql
drupal_db_host: "127.0.0.1"

# Set this to 'false' if you don't need to install Drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: true

# Settings for installing a Drupal site if 'drupal_install_site:' is 'true'.
drupal_domain: "drupaltest.dev"
#drupal_site_name: "Drupal"
drupal_site_name: "boa"
drupal_install_profile: standard
drupal_site_install_extra_args: []
drupal_enable_modules: []
#drupal_account_name: admin
drupal_account_name: boa
#drupal_account_pass: admin
drupal_account_pass: rocks
