---
# Purpose:
# This playbook will copy the master config directory files on the head node to all of the 
# slaves for a particular version of hadoop.

########################################################################################
# start playbook
########################################################################################

- name: Update Hadoop {{ hadoop_version }} configuration files for all nodes.
  hosts: all
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

########################################################################################
# start tasks
########################################################################################


  tasks:
  - name: rm -rf {{ hadoop_conf_dir }}/* on all nodes
    command: rm -rf {{ hadoop_conf_dir }}/*

  - name: copy {{ hadoop_conf_master_dir }} on {{ hadoop_name_node }} to {{ hadoop_conf_dir }} on all nodes
    copy:
      src: "{{ hadoop_conf_master_dir }}"
      dest: "{{ hadoop_conf_dir }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644
