---
# Purpose:
# This playbook will create a directory for the master copies of the configuration files
# for a particular version of hadoop.  

# If the directory does not already exist, this playbook will create a directory and
# copy the files from the configuration directory created while deploying Hadoop for
# this version.
 
# If the master configuration files directory already exists, the program will exit
# to avoid an accidental over write of the master files.

########################################################################################
# start playbook
########################################################################################

- name: Create {{ hadoop_conf_master_dir }} 
  hosts: name_node
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

########################################################################################
# start tasks
########################################################################################

  tasks:
# to ensure you don't delete master configs by accident
  - name: Gather facts about {{ hadoop_conf_master_dir }} and exit if {{ hadoop_conf_master_dir }} already exists
    stat:
      path: "{{ hadoop_conf_master_dir }}"
    register: p

  - fail:
      msg: "{{ hadoop_conf_master_dir }} already exists."
    when: p.stat.isdir is defined and p.stat.isdir

  - name: create "{{ hadoop_conf_master_dir }}"
    file:
      path: "{{ hadoop_conf_master_dir }}"
      state: directory
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

# thanks to the following link i was finally able to figure out how to just copy the files
# , ensure their permissions were set to 0644, but not change the permissions on the directory
# http://www.mydailytutorials.com/how-to-copy-files-and-directories-in-ansible-using-copy-and-fetch-modules/
  - name: copy {{ hadoop_conf_dir }}/* to {{ hadoop_conf_master_dir }}
    copy:
      src:  "{{ hadoop_conf_dir }}/"
      dest: "{{ hadoop_conf_master_dir }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - include: ../../local_includes/delete-ansible-tmp-files.yml
