---
# Purpose:
# This playbook will create a directory for the master copies of the configuration files
# for a particular version of hadoop.  

# If the directory does not already exist, this playbook will create a directory and
# copy the files from the configuration directory created while deploying Hadoop for
# this version.
 
# If the master configuration files directory already exists, the program will exit
# to avoid an accidental over write of the master files.

########################################################################################
# start playbook
########################################################################################

- name: Create {{ hadoop_conf_master_dir }} 
  hosts: name_node
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

########################################################################################
# start tasks
########################################################################################

  tasks:
  - name: Gather facts about {{ hadoop_conf_master_dir }} and exit if {{ hadoop_conf_master_dir }} already exists
    stat:
      path: "{{ hadoop_conf_master_dir }}"
    register: p

  - fail:
      msg: "{{ hadoop_conf_master_dir }} already exists."
    when: p.stat.isdir is defined and p.stat.isdir

  - name: create "{{ hadoop_conf_master_dir }}"
    file:
      path: "{{ hadoop_conf_master_dir }}"
      state: directory
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: cp -r {{ hadoop_conf_dir }}/* {{ hadoop_conf_master_dir }}
    shell: cp -r {{ hadoop_conf_dir }}/* {{ hadoop_conf_master_dir }}
    register: result_val   

  - name: ensure all files are owned by {{ hadoop_user_name }}
    file:
      path:  "{{ hadoop_conf_master_dir }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644
    
  - name: remove "{{ hadoop_conf_master_dir }}" when copy fails
    file:
      path: "{{ hadoop_conf_master_dir }}"
      state: absent
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755
    when: result_val.rc != 0
 
