---
# teardown / dismantle the aws environment

# if i made env vars for the access keys, should remove during this playbook

# if used ssh-agent to add pem file be sure to remove it

- hosts: localhost
  remote_user: ec2-user
  become_method: sudo
  become: true
  gather_facts: no
  connection: local

  vars_files:
    - ./aws-related/aws-cred.yml
    - ./aws-related/aws-vars.yml
    - ./aws-related/vpc-id.yml
    - ./aws-related/subnet-id.yml
    - ./aws-related/igw-id.yml

    