---
# Purpose:
# This playbook will copy the master config directory files on the head node to all of the 
# slaves for a particular version of hadoop.

########################################################################################
# start playbook
########################################################################################

- name: Update Hadoop {{ hadoop_version }} configuration files for all nodes.
  hosts: all
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

########################################################################################
# start tasks
########################################################################################


  tasks:
  - name: remove {{ hadoop_conf_dir }} on each node
    file:
      path: "{{ hadoop_conf_dir }}"
      state: absent

  - name: create {{ hadoop_conf_dir }} on each node
    file:
      path: "{{ hadoop_conf_dir }}"
      state: directory
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

# thanks again to the following link.  it helped correct the error that kept stopping this playbook from working
# http://www.mydailytutorials.com/how-to-copy-files-and-directories-in-ansible-using-copy-and-fetch-modules/
  - name: copy {{ hadoop_conf_master_dir }} files on {{ hadoop_name_node }} to {{ hadoop_conf_dir }} on all nodes
    copy:
      src: "{{ hadoop_conf_master_dir }}/"
      remote_src: false
      dest: "{{ hadoop_conf_dir }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

