---
# Purpose:
# This playbook will format an HDFS filesystem

########################################################################################
# start playbook
########################################################################################

- name: Format HDFS {{ hadoop_version }}
  hosts: name_node
  remote_user: ansible
  become_user: "{{ hadoop_user_name }}"
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

########################################################################################
# start tasks
########################################################################################

  tasks:
# format the namenode
  - name: execute hadoop namenode -format for Hadoop {{ hadoop_version }}
    shell: cd {{ hadoop_install }}/bin; export JAVA_HOME={{ java_home }}; export HADOOP_INSTALL={{ hadoop_install }}; export HADOOP_CONF_DIR={{ hadoop_conf_dir }}; export HADOOP_LOG_DIR={{ hadoop_HADOOP_LOG_DIR }}; export HADOOP_PID_DIR={{ hadoop_HADOOP_PID_DIR }}; ./hadoop namenode -format

# ensure that /data1/version/name and /data2/version/name are of the permission 0755
  - name: Ensure that namenode name directories are 0755
    command: find {{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/{{ hadoop_dfs_name_dir }} -type d -exec chmod 0755 {} \;
    with_sequence: start=1 end={{ hadoop_num_drives_per_node }} stride=1

  - include: ../../local_includes/delete-ansible-tmp-files.yml
