---
# Purpose:
# This playbook will check the cluster for the following processes and start them if stopped:
# name node, job tracker
# secondary name node
# data node, task tracker

########################################################################################
# env vars
########################################################################################

- name: "Set {{ hadoop_version }} environment varibles"
  hosts: name_node
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: redeploy {{ hadoop_env_vars_profile_d_file }}
    template: 
      src: ../local_templates/hadoop-env.j2
      dest: "{{ hadoop_env_vars_profile_d_file }}"
      owner: root
      group: root
      mode:  0644


########################################################################################
# namenode
########################################################################################

- name: Testing namenode for stopped processes
  hosts: name_node
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: Test jps output for NameNode process
    shell: jps
    register: jps_result 

#  - debug:  var=jps_result

  - name: Restarting NameNode
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} start namenode"   
    when: jps_result.stdout | search ("NameNode") == false

  - debug: 
      msg: NameNode is running
    when: jps_result.stdout | search ("NameNode") == true

########################################################################################
# start secondary namenode
########################################################################################

- name: Testing secondary namenode for stopped processes
  hosts: secondary_nn
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: Test jps output for SecondaryNameNode process
    shell: jps
    register: jps_result 

#  - debug:  var=jps_result

  - name: Restarting SecondaryNameNode
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} start secondarynamenode"
    when: jps_result.stdout | search ("SecondaryNameNode") == false

  - debug: 
      msg: SecondaryNameNode is running
    when: jps_result.stdout | search ("SecondaryNameNode") == true


########################################################################################
# start data nodes
########################################################################################
- name: Testing datanode for stopped processes
  hosts: data_nodes
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: Test jps output for DataNode and TaskTracker processes
    shell: jps
    register: jps_result 

#  - debug:  var=jps_result

  - name: Restarting DataNode
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} start datanode"
    when: jps_result.stdout | search ("DataNode") == false

  - name: Restarting TaskTracker
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} start tasktracker"
    when: jps_result.stdout | search ("TaskTracker") == false

  - debug: 
      msg: DataNode is running
    when: jps_result.stdout | search ("DataNode") == true

  - debug: 
      msg: TaskTracker is running
    when: jps_result.stdout | search ("TaskTracker") == true

