---
# Purpose:
# This playbook will start and stop the cluster

########################################################################################
# env vars
########################################################################################


- name: "{{ hadoop_version }} environment varibles"
  hosts: all
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: create {{ hadoop_env_vars_profile_d_file }}
    template: 
      src: ../local_templates/hadoop-env.j2
      dest: "{{ hadoop_env_vars_profile_d_file }}"
      owner: root
      group: root
      mode:  0644
    when: start_stop_cluster == "start"

  - name: remove {{ hadoop_env_vars_profile_d_file }}
    file:
      path:  "{{ hadoop_env_vars_profile_d_file }}"
      state: absent
    when: start_stop_cluster == "stop"

  - include: ../../local_includes/delete-ansible-tmp-files.yml

########################################################################################
# start namenode
########################################################################################
- name: "{{ start_stop_cluster }} namenode"
  hosts: name_node
  remote_user: ansible
  become_user: "{{ hadoop_user_name }}"
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} namenode"
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} namenode"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow namenode to {{ start_stop_cluster }}
    pause:
      seconds: "{{ seconds_to_pause }}"

  - name: "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} jobtracker"
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} jobtracker"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow jobtracker to start
    pause:
      seconds: "{{ seconds_to_pause }}"

  - include: ../../local_includes/delete-ansible-tmp-files.yml


########################################################################################
# start secondary namenode
########################################################################################
- name: "{{ start_stop_cluster }} secondary namenode"
  hosts: secondary_nn
  remote_user: ansible
  become_user: "{{ hadoop_user_name }}"
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} secondarynamenode"
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} secondarynamenode"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow secondary namenode to {{ start_stop_cluster }}
    pause:
      seconds: "{{ seconds_to_pause }}"

  - include: ../../local_includes/delete-ansible-tmp-files.yml


########################################################################################
# start data nodes
########################################################################################
- name: "{{ start_stop_cluster }} datanode"
  hosts: data_nodes
  remote_user: ansible
  become_user: "{{ hadoop_user_name }}"
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/hadoop-vars.yml

  tasks:
  - name: "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} datanode"
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} datanode"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow datanode to {{ start_stop_cluster }}
    pause:
      seconds: "{{ seconds_to_pause }}"

  - name: "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} tasktracker"
    command:  "{{ hadoop_install }}/bin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} {{ start_stop_cluster }} tasktracker"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow tasktracker to {{ start_stop_cluster }}
    pause:
      seconds: "{{ seconds_to_pause }}"

  - include: ../../local_includes/delete-ansible-tmp-files.yml
