--- # testing how to create an array or dict or something

- name: testing
  hosts: head
  remote_user: ansible
#  remote_user: brian
  become_user: root
  become: true
  become_method: sudo
#  ask_sudo_pass: true
  connection: ssh
  gather_facts: no

  vars_files:
    - ./local_variable_files/hadoop-vars.yml

#  vars:
#    redis_instances: 5

  tasks:
  - name: name
    with_sequence: start=1 end={{ cluster_num_drives_per_node }}
    debug: msg="{{ hadoop_data_base_dir }}{{ item }}/{{ hadoop_version }}/name"
    register: dfs_name_dir_seq


  - set_fact:
      dfs_name_dir_list1: "{{ dfs_name_dir_seq.results | map(attribute='msg') | join(',') }}"
      dfs_name_dir_list2: "{{ dfs_name_dir_seq.results | map(attribute='msg') }}"

  - debug: var=dfs_name_dir_seq
  - debug: var=dfs_name_dir_list1
  - debug: var=dfs_name_dir_list2


