---
# Purpose:
# This playbook will delete spark from all nodes.
# Basically, it is a convenience playbook for iterative testing.
# It saves me from having to delete all the directories by hand.

########################################################################################
# start playbook
########################################################################################
- name: Delete Spark {{ spark_version }}
  hosts: all
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo 
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/spark-vars.yml

########################################################################################
# start tasks
########################################################################################

  tasks:
  - name: rm -rf {{ spark_home }}
    file:
      path: "{{ spark_home }}"
      state: absent


