---
# ASSUMES Hadoop 1.2.1 

- name: Install the remaining boa items
  hosts: name_node
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo 
  connection: ssh
  gather_facts: no

  vars_files:
    - ../hadoop1-playbooks/local_variable_files/hadoop-vars.yml

  vars:
    seconds_to_pause: 5


  tasks:
  - name: create ~/hadoop/bin if does not exist
    file:
      path: "{{ hadoop_user_home }}/bin/"
      state: directory
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/BoaCompilePoller.java
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/BoaCompilePoller.java
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: http://boa.cs.iastate.edu/cloudlab/run-poller.sh
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/run-poller.sh
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/boa-compile.sh
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-compile.sh
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/boa-run.sh
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-run.sh
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: create ~/hadoop/complier/live/dist if does not exist
    file:
      path: "{{ hadoop_user_home }}/compiler/live/dist/"
      state: directory
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/boa-compiler.jar
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-compiler.jar
      dest: "{{ hadoop_user_home }}/compiler/live/dist/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: http://boa.cs.iastate.edu/cloudlab/boa-runtime.jar
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-runtime.jar
      dest: "{{ hadoop_user_home }}/compiler/live/dist/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: make sure {{ hadoop_user_name }} is the owner of all {{ hadoop_user_home }} files
    file:
      path: "{{ hadoop_user_home }}"
      group: "{{ hadoop_user_group }}"
      owner: "{{ hadoop_user_name }}"
      recurse: yes

#######################
  - name: get http://boa.cs.iastate.edu/cloudlab/index
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/index
      dest: "{{ hadoop_user_home }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

# run first to create directories
  - name: "{{ hadoop_base }}/1.2.1/bin/hadoop dfs -mkdir /repcache/live/ast"
    shell: su - {{ hadoop_user_name }} -c "export JAVA_HOME={{ java_home }}; {{ hadoop_base }}/1.2.1/bin/hadoop dfs -mkdir /repcache/live/ast"

  - name: "{{ hadoop_base }}/1.2.1/bin/hadoop dfs -copyFromLocal index /repcache/live/ast"
    shell: su - {{ hadoop_user_name }} -c "export JAVA_HOME={{ java_home }}; {{ hadoop_base }}/1.2.1/bin/hadoop dfs -copyFromLocal index /repcache/live/ast"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow hadoop dfs -copyFromLocal ast /repcache/live
    pause:
      seconds: "{{ seconds_to_pause }}"

  - name: rm {{ hadoop_user_home }}/index
    file:
      path: "{{ hadoop_user_home }}/index"
      state: absent

#######################
  - name: get http://boa.cs.iastate.edu/cloudlab/data
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/data
      dest: "{{ hadoop_user_home }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: "{{ hadoop_base }}/1.2.1/bin/hadoop dfs -copyFromLocal data /repcache/live/ast"
    shell: su - {{ hadoop_user_name }} -c "export JAVA_HOME={{ java_home }}; {{ hadoop_base }}/1.2.1/bin/hadoop dfs -copyFromLocal data /repcache/live/ast"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow hadoop dfs -copyFromLocal data /repcache/live
    pause:
      seconds: "{{ seconds_to_pause }}"

  - name: rm {{ hadoop_user_home }}/data
    file:
      path: "{{ hadoop_user_home }}/data"
      state: absent

#######################
  - name: get http://boa.cs.iastate.edu/cloudlab/projects.seq
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/projects.seq
      dest: "{{ hadoop_user_home }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: "{{ hadoop_base }}/1.2.1/bin/hadoop dfs -copyFromLocal projects.seq /repcache/live"
    shell: su - {{ hadoop_user_name }} -c "export JAVA_HOME={{ java_home }}; {{ hadoop_base }}/1.2.1/bin/hadoop dfs -copyFromLocal projects.seq /repcache/live"

  - name: Pause playbook {{ seconds_to_pause }} seconds to allow hadoop dfs -copyFromLocal projects.seq /repcache/live
    pause:
      seconds: "{{ seconds_to_pause }}"

  - name: rm {{ hadoop_user_home }}/projects.seq
    file:
      path: "{{ hadoop_user_home }}/projects.seq"
      state: absent

  - cron:
      name: "run BoaCompilerPoller"
      minute: "*/10"
      user: "{{ hadoop_user_name }}"
      job: "jps|grep BoaCompilePoller >/dev/null ; if [ $? -eq 1 ]; then cd /home/hadoop/bin ; exec ./run-poller >/dev/null 2>&1 ; fi"

  - cron:
      name: "kill BoaCompilerPoller"
      minute: 9
      hour: 4
      user: "{{ hadoop_user_name }}"
      job: "jps|grep BoaCompilePoller|cut -f1 -d' '|xargs kill -9 >/dev/null 2>&1"

  - name: install at
    apt:
      name: at
      state: present

  - at:
      command: su - {{ hadoop_user_name }} -c "exec /home/hadoop/bin/run-poller.sh >/dev/null 2>&1"
      count: 1
      units: minutes

  - include: ../local_includes/delete-ansible-tmp-files.yml
