---
# ASSUMES Hadoop 1.2.1

- name: Install the remaining boa items
  hosts: name_node
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo 
  connection: ssh
  gather_facts: no

  vars_files:
    - ../hadoop1-playbooks/local_variable_files/hadoop-vars.yml


  tasks:
  - name: create ~/hadoop/bin if does not exist
    file:
      path: "{{ hadoop_user_home }}/bin/"
      state: directory
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/BoaCompilePoller.java
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/BoaCompilePoller.java
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: http://boa.cs.iastate.edu/cloudlab/run-poller.sh
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/run-poller.sh
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/boa-compile.sh
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-compile.sh
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/boa-run.sh
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-run.sh
      dest: "{{ hadoop_user_home }}/bin/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0755

  - name: create ~/hadoop/complier/live/dist if does not exist
    file:
      path: "{{ hadoop_user_home }}/compiler/live/dist/"
      state: directory
      mode: 0755

  - name: http://boa.cs.iastate.edu/cloudlab/boa-compiler.jar
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-compiler.jar
      dest: "{{ hadoop_user_home }}/compiler/live/dist/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: http://boa.cs.iastate.edu/cloudlab/boa-runtime.jar
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/boa-runtime.jar
      dest: "{{ hadoop_user_home }}/compiler/live/dist/"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - cron:
      name: "run BoaCompilerPoller"
      minute: "*/10"
      job: "jps|grep BoaCompilePoller >/dev/null ; if [ $? -eq 1 ]; then cd /home/hadoop/bin ; exec ./run-poller >/dev/null 2>&1 ; fi"

  - cron:
      name: "kill BoaCompilerPoller"
      minute: 9
      hour: 4
      job: "jps|grep BoaCompilePoller|cut -f1 -d' '|xargs kill -9 >/dev/null 2>&1"

#######################
  - name: get http://boa.cs.iastate.edu/cloudlab/index
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/index
      dest: "{{ hadoop_user_home }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

# run first to create all directories
  - name: hadoop dfs -mkdir /repcache/live/ast
    become_user: "{{ hadoop_user_name }}"
    become: true
    shell: hadoop dfs -mkdir /repcache/live/ast
    args:
      chdir: "{{ hadoop_user_home }}"

  - name: copy http://boa.cs.iastate.edu/cloudlab/index to HDFS /repcache/live/ast/index
    become_user: "{{ hadoop_user_name }}"
    become: true
    shell: hadoop dfs -copyFromLocal index /repcache/live/ast
    args:
      chdir: "{{ hadoop_user_home }}"

  - name: rm {{ hadoop_user_home }}/index
    file:
      path: "{{ hadoop_user_home }}/index"
      state: absent

#######################
  - name: get http://boa.cs.iastate.edu/cloudlab/data
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/data
      dest: "{{ hadoop_user_home }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: transfer http://boa.cs.iastate.edu/cloudlab/data to HDFS /repcache/live/ast/data
    become_user: "{{ hadoop_user_name }}"
    become: true
    shell: hadoop dfs -copyFromLocal data /repcache/live/ast
    args:
      chdir: "{{ hadoop_user_home }}"

  - name: rm {{ hadoop_user_home }}/data
    file:
      path: "{{ hadoop_user_home }}/data"
      state: absent

#######################
  - name: get http://boa.cs.iastate.edu/cloudlab/projects.seq
    get_url: 
      url: http://boa.cs.iastate.edu/cloudlab/projects.seq
      dest: "{{ hadoop_user_home }}"
      owner: "{{ hadoop_user_name }}"
      group: "{{ hadoop_user_group }}"
      mode: 0644

  - name: transfer http://boa.cs.iastate.edu/cloudlab/projects.seq to HDFS /repcache/live/projects.seq
    become_user: "{{ hadoop_user_name }}"
    become: true
    shell: hadoop dfs -copyFromLocal projects.seq /repcache/live
    args:
      chdir: "{{ hadoop_user_home }}"

  - name: rm {{ hadoop_user_home }}/projects.seq
    file:
      path: "{{ hadoop_user_home }}/projects.seq"
      state: absent



